wires = ['XXX']
cnt = {}
rules = 0

for i in range(20):
    w = input().strip()
    wires.append(w)
    if w not in cnt:
        cnt[w] = 0
    cnt[w] += 1

def add_key(k):
    global rules
    rules += 1
    if k not in cnt:
        cnt[k] = 0

def cut_wire(w):
    print('Cut wire ' + str(w))
    # print(rules)
    # print('(On rule ' + str(rules) + ')')
    exit(0)

add_key('none')
if wires[17] == 'silver': cut_wire(10)
add_key('none')
if wires[20] == 'wine': cut_wire(20)
add_key('gold')
if cnt['gold'] == 18: cut_wire(8)
add_key('none')
if wires[12] == 'pearl': cut_wire(11)
add_key('caramel')
if cnt['caramel'] == 14: cut_wire(11)
add_key('oyster')
if cnt['oyster'] >= 11: cut_wire(16)
add_key('seaweed')
if cnt['seaweed'] == 12: cut_wire(5)
add_key('emerald')
if cnt['emerald'] >= 18: cut_wire(4)
add_key('fire')
if cnt['fire'] >= 14: cut_wire(1)
add_key('lapis')
if cnt['lapis'] == 18: cut_wire(3)
add_key('none')
if wires[11] == 'berry': cut_wire(2)
add_key('pineapple')
if cnt['pineapple'] == 1: cut_wire(12)
add_key('blood')
if cnt['blood'] == 1: cut_wire(15)
add_key('green')
if cnt['green'] == 4: cut_wire(16)
add_key('none')
if wires[20] == 'fern': cut_wire(6)
add_key('none')
if wires[8] == 'berry': cut_wire(14)
add_key('navy')
if cnt['navy'] == 12: cut_wire(5)
add_key('none')
if wires[4] == 'peach': cut_wire(9)
add_key('apricot')
if cnt['apricot'] >= 7: cut_wire(17)
add_key('none')
if wires[7] == 'obsidian': cut_wire(16)
add_key('ruby')
if cnt['ruby'] == 13: cut_wire(15)
add_key('none')
if wires[15] == 'black': cut_wire(8)
add_key('grape')
if cnt['grape'] == 17: cut_wire(17)
add_key('granola')
if cnt['granola'] == 2: cut_wire(16)
add_key('macaroon')
if cnt['macaroon'] == 15: cut_wire(7)
add_key('iris')
if cnt['iris'] >= 8: cut_wire(7)
add_key('none')
if wires[13] == 'cobalt': cut_wire(1)
add_key('hickory')
if cnt['hickory'] == 8: cut_wire(12)
add_key('none')
if wires[11] == 'wine': cut_wire(3)
add_key('none')
if wires[8] == 'charcoal': cut_wire(10)
add_key('none')
if wires[13] == 'silver': cut_wire(10)
add_key('none')
if wires[16] == 'dijon': cut_wire(19)
add_key('caramel')
if cnt['caramel'] >= 9: cut_wire(4)
add_key('squash')
if cnt['squash'] == 9: cut_wire(5)
add_key('none')
if wires[16] == 'tortilla': cut_wire(7)
add_key('none')
if wires[4] == 'white': cut_wire(18)
add_key('hickory')
if cnt['hickory'] == 16: cut_wire(2)
add_key('coconut')
if cnt['coconut'] == 5: cut_wire(2)
add_key('fawn')
if cnt['fawn'] >= 19: cut_wire(13)
add_key('white')
if cnt['white'] == 14: cut_wire(12)
add_key('none')
if wires[10] == 'buttermilk': cut_wire(1)
add_key('orange')
if cnt['orange'] == 17: cut_wire(12)
add_key('gray')
if cnt['gray'] == 19: cut_wire(7)
add_key('banana')
if cnt['banana'] == 5: cut_wire(16)
add_key('none')
if wires[10] == 'marigold': cut_wire(9)
add_key('red')
if cnt['red'] == 12: cut_wire(14)
add_key('none')
if wires[4] == 'ivory': cut_wire(12)
add_key('carrot')
if cnt['carrot'] == 15: cut_wire(5)
add_key('bronze')
if cnt['bronze'] == 11: cut_wire(6)
add_key('corn')
if cnt['corn'] == 9: cut_wire(4)
add_key('marigold')
if cnt['marigold'] == 13: cut_wire(17)
add_key('white')
if cnt['white'] == 12: cut_wire(17)
add_key('carrot')
if cnt['carrot'] >= 7: cut_wire(18)
add_key('none')
if wires[10] == 'seaweed': cut_wire(15)
add_key('none')
if wires[16] == 'pickle': cut_wire(16)
add_key('none')
if wires[16] == 'green': cut_wire(4)
add_key('rust')
if cnt['rust'] == 13: cut_wire(18)
add_key('porcelain')
if cnt['porcelain'] == 15: cut_wire(3)
add_key('cobalt')
if cnt['cobalt'] == 2: cut_wire(4)
add_key('blood')
if cnt['blood'] == 2: cut_wire(16)
add_key('sandstone')
if cnt['sandstone'] == 18: cut_wire(8)
add_key('candy')
if cnt['candy'] >= 8: cut_wire(2)
add_key('violet')
if cnt['violet'] >= 9: cut_wire(11)
add_key('none')
if wires[16] == 'green': cut_wire(14)
add_key('arctic')
if cnt['arctic'] == 17: cut_wire(1)
add_key('wood')
if cnt['wood'] == 18: cut_wire(1)
add_key('fern')
if cnt['fern'] == 12: cut_wire(8)
add_key('none')
if wires[10] == 'orchid': cut_wire(14)
add_key('dijon')
if cnt['dijon'] == 11: cut_wire(14)
add_key('rose')
if cnt['rose'] == 19: cut_wire(13)
add_key('crimson')
if cnt['crimson'] == 12: cut_wire(10)
add_key('stone')
if cnt['stone'] == 6: cut_wire(13)
add_key('none')
if wires[20] == 'green': cut_wire(20)
add_key('rose')
if cnt['rose'] == 6: cut_wire(15)
add_key('none')
if wires[16] == 'cloud': cut_wire(5)
add_key('gold')
if cnt['gold'] == 5: cut_wire(19)
add_key('none')
if wires[5] == 'fawn': cut_wire(11)
add_key('green')
if cnt['green'] >= 12: cut_wire(14)
add_key('squash')
if cnt['squash'] == 12: cut_wire(13)
add_key('none')
if wires[15] == 'rouge': cut_wire(12)
add_key('none')
if wires[8] == 'watermelon': cut_wire(18)
add_key('none')
if wires[20] == 'tan': cut_wire(5)
add_key('orchid')
if cnt['orchid'] == 17: cut_wire(9)
add_key('none')
if wires[17] == 'dijon': cut_wire(3)
add_key('rouge')
if cnt['rouge'] == 20: cut_wire(13)
add_key('rouge')
if cnt['rouge'] >= 14: cut_wire(9)
add_key('teal')
if cnt['teal'] == 12: cut_wire(19)
add_key('red')
if cnt['red'] == 15: cut_wire(15)
add_key('none')
if wires[13] == 'sand': cut_wire(3)
add_key('none')
if wires[11] == 'obsidian': cut_wire(15)
add_key('macaroon')
if cnt['macaroon'] == 10: cut_wire(20)
add_key('none')
if wires[3] == 'gray': cut_wire(4)
add_key('none')
if wires[14] == 'bone': cut_wire(7)
add_key('marmalade')
if cnt['marmalade'] == 9: cut_wire(13)
add_key('navy')
if cnt['navy'] >= 15: cut_wire(7)
add_key('apricot')
if cnt['apricot'] == 16: cut_wire(5)
add_key('scarlet')
if cnt['scarlet'] == 14: cut_wire(11)
add_key('none')
if wires[8] == 'fawn': cut_wire(5)
add_key('gray')
if cnt['gray'] == 20: cut_wire(14)
add_key('apricot')
if cnt['apricot'] >= 7: cut_wire(8)
add_key('arctic')
if cnt['arctic'] == 10: cut_wire(8)
add_key('silver')
if cnt['silver'] == 4: cut_wire(2)
add_key('none')
if wires[7] == 'basil': cut_wire(13)
add_key('silver')
if cnt['silver'] == 7: cut_wire(5)
add_key('none')
if wires[1] == 'dijon': cut_wire(20)
add_key('none')
if wires[4] == 'pineapple': cut_wire(14)
add_key('none')
if wires[10] == 'ruby': cut_wire(1)
add_key('pearl')
if cnt['pearl'] == 19: cut_wire(9)
add_key('none')
if wires[8] == 'fern': cut_wire(17)
add_key('bronze')
if cnt['bronze'] == 7: cut_wire(2)
add_key('none')
if wires[6] == 'rose': cut_wire(19)
add_key('rose')
if cnt['rose'] == 18: cut_wire(1)
add_key('basil')
if cnt['basil'] == 1: cut_wire(6)
add_key('white')
if cnt['white'] == 8: cut_wire(5)
add_key('crepe')
if cnt['crepe'] == 11: cut_wire(3)
add_key('ash')
if cnt['ash'] == 4: cut_wire(7)
add_key('none')
if wires[3] == 'orchid': cut_wire(18)
add_key('bubblegum')
if cnt['bubblegum'] == 5: cut_wire(15)
add_key('none')
if wires[2] == 'shortbread': cut_wire(5)
add_key('gold')
if cnt['gold'] == 6: cut_wire(20)
add_key('hickory')
if cnt['hickory'] == 19: cut_wire(10)
add_key('none')
if wires[15] == 'yellow': cut_wire(12)
add_key('iris')
if cnt['iris'] == 13: cut_wire(4)
add_key('none')
if wires[10] == 'daisy': cut_wire(10)
add_key('none')
if wires[4] == 'chiffon': cut_wire(20)
add_key('hazelnut')
if cnt['hazelnut'] >= 13: cut_wire(3)
add_key('macaroon')
if cnt['macaroon'] == 16: cut_wire(6)
add_key('ivory')
if cnt['ivory'] >= 14: cut_wire(6)
add_key('none')
if wires[11] == 'cotton': cut_wire(13)
add_key('squash')
if cnt['squash'] == 9: cut_wire(20)
add_key('none')
if wires[10] == 'cherry': cut_wire(18)
add_key('sandstone')
if cnt['sandstone'] == 2: cut_wire(16)
add_key('none')
if wires[5] == 'arctic': cut_wire(5)
add_key('violet')
if cnt['violet'] >= 14: cut_wire(12)
add_key('orchid')
if cnt['orchid'] >= 14: cut_wire(11)
add_key('peach')
if cnt['peach'] == 8: cut_wire(4)
add_key('none')
if wires[10] == 'navy': cut_wire(16)
add_key('arctic')
if cnt['arctic'] == 13: cut_wire(20)
add_key('dijon')
if cnt['dijon'] >= 19: cut_wire(11)
add_key('coral')
if cnt['coral'] == 1: cut_wire(11)
add_key('marigold')
if cnt['marigold'] == 16: cut_wire(2)
add_key('lapis')
if cnt['lapis'] == 18: cut_wire(10)
add_key('rouge')
if cnt['rouge'] >= 16: cut_wire(10)
add_key('peach')
if cnt['peach'] == 2: cut_wire(15)
add_key('gold')
if cnt['gold'] == 6: cut_wire(5)
add_key('azure')
if cnt['azure'] == 9: cut_wire(12)
add_key('azure')
if cnt['azure'] == 18: cut_wire(15)
add_key('butter')
if cnt['butter'] == 16: cut_wire(14)
add_key('oyster')
if cnt['oyster'] == 17: cut_wire(13)
add_key('gold')
if cnt['gold'] >= 16: cut_wire(14)
add_key('coffee')
if cnt['coffee'] == 5: cut_wire(13)
add_key('eggplant')
if cnt['eggplant'] == 4: cut_wire(12)
add_key('none')
if wires[2] == 'grape': cut_wire(17)
add_key('crimson')
if cnt['crimson'] == 5: cut_wire(15)
add_key('tan')
if cnt['tan'] == 18: cut_wire(12)
add_key('bubblegum')
if cnt['bubblegum'] == 8: cut_wire(11)
add_key('rose')
if cnt['rose'] == 13: cut_wire(9)
add_key('white')
if cnt['white'] == 5: cut_wire(16)
add_key('none')
if wires[5] == 'watermelon': cut_wire(20)
add_key('violet')
if cnt['violet'] == 9: cut_wire(7)
add_key('none')
if wires[17] == 'pink': cut_wire(7)
add_key('lapis')
if cnt['lapis'] >= 10: cut_wire(3)
add_key('watermelon')
if cnt['watermelon'] == 19: cut_wire(7)
add_key('none')
if wires[14] == 'green': cut_wire(11)
add_key('none')
if wires[5] == 'blush': cut_wire(18)
add_key('sandstone')
if cnt['sandstone'] == 4: cut_wire(12)
add_key('none')
if wires[8] == 'charcoal': cut_wire(16)
add_key('none')
if wires[13] == 'crepe': cut_wire(3)
add_key('bronze')
if cnt['bronze'] == 18: cut_wire(10)
add_key('fawn')
if cnt['fawn'] == 16: cut_wire(5)
add_key('candy')
if cnt['candy'] == 12: cut_wire(15)
add_key('jade')
if cnt['jade'] == 11: cut_wire(13)
add_key('chiffon')
if cnt['chiffon'] == 13: cut_wire(20)
add_key('sage')
if cnt['sage'] == 7: cut_wire(6)
add_key('none')
if wires[18] == 'green': cut_wire(1)
add_key('none')
if wires[10] == 'charcoal': cut_wire(4)
add_key('none')
if wires[9] == 'honey': cut_wire(9)
add_key('blood')
if cnt['blood'] == 12: cut_wire(12)
add_key('none')
if wires[1] == 'banana': cut_wire(8)
add_key('teal')
if cnt['teal'] == 5: cut_wire(7)
add_key('orange')
if cnt['orange'] == 10: cut_wire(15)
add_key('blush')
if cnt['blush'] == 17: cut_wire(5)
add_key('lapis')
if cnt['lapis'] == 9: cut_wire(15)
add_key('pear')
if cnt['pear'] >= 19: cut_wire(10)
add_key('none')
if wires[7] == 'pear': cut_wire(20)
add_key('none')
if wires[18] == 'blush': cut_wire(2)
add_key('none')
if wires[16] == 'chiffon': cut_wire(19)
add_key('none')
if wires[17] == 'orchid': cut_wire(4)
add_key('pink')
if cnt['pink'] == 17: cut_wire(17)
add_key('none')
if wires[6] == 'blood': cut_wire(9)
add_key('none')
if wires[19] == 'grape': cut_wire(19)
add_key('none')
if wires[9] == 'cherry': cut_wire(18)
add_key('basil')
if cnt['basil'] == 4: cut_wire(4)
add_key('violet')
if cnt['violet'] >= 10: cut_wire(15)
add_key('rosewood')
if cnt['rosewood'] == 14: cut_wire(4)
add_key('arctic')
if cnt['arctic'] == 4: cut_wire(11)
add_key('none')
if wires[8] == 'honey': cut_wire(18)
add_key('flint')
if cnt['flint'] == 12: cut_wire(14)
add_key('violet')
if cnt['violet'] == 3: cut_wire(13)
add_key('jade')
if cnt['jade'] == 2: cut_wire(5)
add_key('shamrock')
if cnt['shamrock'] >= 15: cut_wire(5)
add_key('none')
if wires[7] == 'cotton': cut_wire(14)
add_key('rosewood')
if cnt['rosewood'] == 2: cut_wire(4)
add_key('blush')
if cnt['blush'] == 2: cut_wire(17)
add_key('none')
if wires[17] == 'hazelnut': cut_wire(13)
add_key('none')
if wires[3] == 'rust': cut_wire(15)
add_key('candy')
if cnt['candy'] == 5: cut_wire(7)
add_key('teal')
if cnt['teal'] == 15: cut_wire(19)
add_key('iris')
if cnt['iris'] == 5: cut_wire(4)
add_key('none')
if wires[14] == 'brown': cut_wire(13)
add_key('none')
if wires[17] == 'crepe': cut_wire(15)
add_key('coffee')
if cnt['coffee'] == 20: cut_wire(9)
add_key('none')
if wires[11] == 'candy': cut_wire(15)
add_key('none')
if wires[7] == 'scarlet': cut_wire(9)
add_key('coffee')
if cnt['coffee'] == 8: cut_wire(17)
add_key('hickory')
if cnt['hickory'] == 19: cut_wire(4)
add_key('cloud')
if cnt['cloud'] == 18: cut_wire(17)
add_key('chocolate')
if cnt['chocolate'] >= 17: cut_wire(4)
add_key('bronze')
if cnt['bronze'] == 5: cut_wire(13)
add_key('none')
if wires[4] == 'teal': cut_wire(1)
add_key('iris')
if cnt['iris'] == 20: cut_wire(13)
add_key('none')
if wires[8] == 'ash': cut_wire(10)
add_key('sand')
if cnt['sand'] >= 12: cut_wire(4)
add_key('none')
if wires[3] == 'chiffon': cut_wire(15)
add_key('red')
if cnt['red'] == 8: cut_wire(18)
add_key('none')
if wires[18] == 'carrot': cut_wire(7)
add_key('none')
if wires[18] == 'stone': cut_wire(10)
add_key('none')
if wires[2] == 'pink': cut_wire(19)
add_key('tiger')
if cnt['tiger'] == 15: cut_wire(7)
add_key('lime')
if cnt['lime'] >= 16: cut_wire(17)
add_key('caramel')
if cnt['caramel'] == 20: cut_wire(19)
add_key('violet')
if cnt['violet'] == 18: cut_wire(4)
add_key('none')
if wires[1] == 'sage': cut_wire(16)
add_key('corn')
if cnt['corn'] >= 8: cut_wire(5)
add_key('none')
if wires[2] == 'penny': cut_wire(19)
add_key('teal')
if cnt['teal'] == 4: cut_wire(10)
add_key('none')
if wires[2] == 'iris': cut_wire(18)
add_key('none')
if wires[8] == 'iris': cut_wire(5)
add_key('sage')
if cnt['sage'] >= 18: cut_wire(1)
add_key('none')
if wires[12] == 'red': cut_wire(11)
add_key('none')
if wires[19] == 'tiger': cut_wire(8)
add_key('sage')
if cnt['sage'] == 13: cut_wire(19)
add_key('none')
if wires[6] == 'lime': cut_wire(4)
add_key('flint')
if cnt['flint'] == 8: cut_wire(20)
add_key('ruby')
if cnt['ruby'] == 18: cut_wire(20)
add_key('none')
if wires[19] == 'corn': cut_wire(12)
add_key('honey')
if cnt['honey'] >= 12: cut_wire(12)
add_key('watermelon')
if cnt['watermelon'] == 6: cut_wire(16)
add_key('none')
if wires[5] == 'marmalade': cut_wire(8)
add_key('porcelain')
if cnt['porcelain'] == 18: cut_wire(13)
add_key('pineapple')
if cnt['pineapple'] == 8: cut_wire(19)
add_key('tiger')
if cnt['tiger'] == 17: cut_wire(10)
add_key('azure')
if cnt['azure'] == 1: cut_wire(6)
add_key('teal')
if cnt['teal'] == 16: cut_wire(17)
add_key('none')
if wires[7] == 'sky': cut_wire(20)
add_key('hazelnut')
if cnt['hazelnut'] == 20: cut_wire(16)
add_key('magenta')
if cnt['magenta'] == 7: cut_wire(12)
add_key('crimson')
if cnt['crimson'] >= 13: cut_wire(20)
add_key('none')
if wires[17] == 'green': cut_wire(3)
add_key('rosewood')
if cnt['rosewood'] == 11: cut_wire(1)
add_key('none')
if wires[10] == 'corn': cut_wire(15)
add_key('none')
if wires[19] == 'dijon': cut_wire(14)
add_key('gray')
if cnt['gray'] == 5: cut_wire(10)
add_key('macaroon')
if cnt['macaroon'] == 16: cut_wire(16)
add_key('bronze')
if cnt['bronze'] == 19: cut_wire(8)
add_key('none')
if wires[9] == 'pink': cut_wire(13)
add_key('marmalade')
if cnt['marmalade'] == 10: cut_wire(1)
add_key('none')
if wires[8] == 'hazelnut': cut_wire(4)
add_key('none')
if wires[19] == 'bronze': cut_wire(13)
add_key('coconut')
if cnt['coconut'] == 2: cut_wire(10)
add_key('none')
if wires[8] == 'sage': cut_wire(7)
add_key('buttermilk')
if cnt['buttermilk'] == 16: cut_wire(7)
add_key('none')
if wires[14] == 'chiffon': cut_wire(19)
add_key('none')
if wires[10] == 'brown': cut_wire(16)
add_key('rosewood')
if cnt['rosewood'] == 6: cut_wire(8)
add_key('pear')
if cnt['pear'] >= 17: cut_wire(9)
add_key('magenta')
if cnt['magenta'] >= 10: cut_wire(8)
add_key('peach')
if cnt['peach'] == 12: cut_wire(15)
add_key('teal')
if cnt['teal'] == 2: cut_wire(13)
add_key('none')
if wires[19] == 'buttermilk': cut_wire(13)
add_key('none')
if wires[1] == 'honey': cut_wire(3)
add_key('granola')
if cnt['granola'] == 8: cut_wire(19)
add_key('teal')
if cnt['teal'] == 20: cut_wire(6)
add_key('none')
if wires[15] == 'white': cut_wire(14)
add_key('granola')
if cnt['granola'] >= 16: cut_wire(13)
add_key('none')
if wires[11] == 'pink': cut_wire(2)
add_key('candy')
if cnt['candy'] >= 16: cut_wire(15)
add_key('none')
if wires[19] == 'apricot': cut_wire(14)
add_key('candy')
if cnt['candy'] == 19: cut_wire(20)
add_key('watermelon')
if cnt['watermelon'] >= 12: cut_wire(1)
add_key('honey')
if cnt['honey'] == 5: cut_wire(11)
add_key('shortbread')
if cnt['shortbread'] == 16: cut_wire(8)
add_key('pickle')
if cnt['pickle'] >= 13: cut_wire(1)
add_key('plum')
if cnt['plum'] == 9: cut_wire(2)
add_key('none')
if wires[1] == 'iris': cut_wire(8)
add_key('coconut')
if cnt['coconut'] == 16: cut_wire(10)
add_key('green')
if cnt['green'] == 17: cut_wire(19)
add_key('none')
if wires[11] == 'dijon': cut_wire(13)
add_key('grape')
if cnt['grape'] == 15: cut_wire(15)
add_key('none')
if wires[11] == 'orchid': cut_wire(1)
add_key('rouge')
if cnt['rouge'] >= 7: cut_wire(3)
add_key('seaweed')
if cnt['seaweed'] == 1: cut_wire(13)
add_key('cotton')
if cnt['cotton'] == 16: cut_wire(16)
add_key('none')
if wires[16] == 'shortbread': cut_wire(3)
add_key('black')
if cnt['black'] == 19: cut_wire(3)
add_key('marigold')
if cnt['marigold'] == 7: cut_wire(9)
add_key('none')
if wires[16] == 'granola': cut_wire(4)
add_key('scarlet')
if cnt['scarlet'] == 19: cut_wire(12)
add_key('none')
if wires[5] == 'berry': cut_wire(9)
add_key('sandstone')
if cnt['sandstone'] == 5: cut_wire(1)
add_key('none')
if wires[5] == 'pearl': cut_wire(16)
add_key('candy')
if cnt['candy'] == 4: cut_wire(10)
add_key('none')
if wires[2] == 'coral': cut_wire(8)
add_key('none')
if wires[2] == 'basil': cut_wire(5)
add_key('none')
if wires[1] == 'pearl': cut_wire(5)
add_key('arctic')
if cnt['arctic'] == 14: cut_wire(3)
add_key('none')
if wires[15] == 'azure': cut_wire(15)
add_key('teal')
if cnt['teal'] == 7: cut_wire(4)
add_key('none')
if wires[8] == 'honey': cut_wire(7)
add_key('hickory')
if cnt['hickory'] >= 7: cut_wire(11)
add_key('bone')
if cnt['bone'] == 1: cut_wire(13)
add_key('scarlet')
if cnt['scarlet'] == 16: cut_wire(17)
add_key('iron')
if cnt['iron'] == 16: cut_wire(4)
add_key('pearl')
if cnt['pearl'] == 18: cut_wire(2)
add_key('none')
if wires[20] == 'lead': cut_wire(18)
add_key('none')
if wires[20] == 'scarlet': cut_wire(12)
add_key('caramel')
if cnt['caramel'] == 19: cut_wire(16)
add_key('macaroon')
if cnt['macaroon'] == 13: cut_wire(8)
add_key('jade')
if cnt['jade'] == 2: cut_wire(16)
add_key('lead')
if cnt['lead'] == 9: cut_wire(17)
add_key('macaroon')
if cnt['macaroon'] == 18: cut_wire(18)
add_key('jade')
if cnt['jade'] == 2: cut_wire(19)
add_key('none')
if wires[16] == 'banana': cut_wire(7)
add_key('cherry')
if cnt['cherry'] == 10: cut_wire(12)
add_key('tiger')
if cnt['tiger'] == 14: cut_wire(4)
add_key('sky')
if cnt['sky'] == 16: cut_wire(20)
add_key('none')
if wires[8] == 'marigold': cut_wire(4)
add_key('rouge')
if cnt['rouge'] == 15: cut_wire(19)
add_key('banana')
if cnt['banana'] == 6: cut_wire(20)
add_key('pear')
if cnt['pear'] == 20: cut_wire(14)
add_key('magenta')
if cnt['magenta'] == 8: cut_wire(13)
add_key('none')
if wires[16] == 'ivory': cut_wire(5)
add_key('none')
if wires[5] == 'iron': cut_wire(8)
add_key('pearl')
if cnt['pearl'] == 6: cut_wire(6)
add_key('lime')
if cnt['lime'] == 18: cut_wire(20)
add_key('none')
if wires[13] == 'fawn': cut_wire(16)
add_key('charcoal')
if cnt['charcoal'] == 11: cut_wire(15)
add_key('none')
if wires[13] == 'hazelnut': cut_wire(16)
add_key('porcelain')
if cnt['porcelain'] == 7: cut_wire(1)
add_key('purple')
if cnt['purple'] >= 15: cut_wire(11)
add_key('none')
if wires[10] == 'brown': cut_wire(9)
add_key('sage')
if cnt['sage'] == 5: cut_wire(8)
add_key('none')
if wires[2] == 'jade': cut_wire(17)
add_key('tan')
if cnt['tan'] == 1: cut_wire(2)
add_key('none')
if wires[2] == 'jade': cut_wire(5)
add_key('rose')
if cnt['rose'] == 8: cut_wire(5)
add_key('none')
if wires[18] == 'lead': cut_wire(7)
add_key('charcoal')
if cnt['charcoal'] == 2: cut_wire(5)
add_key('none')
if wires[11] == 'marmalade': cut_wire(5)
add_key('none')
if wires[14] == 'crepe': cut_wire(9)
add_key('none')
if wires[7] == 'sky': cut_wire(5)
add_key('none')
if wires[19] == 'candy': cut_wire(9)
add_key('grape')
if cnt['grape'] == 1: cut_wire(11)
add_key('lapis')
if cnt['lapis'] >= 16: cut_wire(2)
add_key('crimson')
if cnt['crimson'] == 14: cut_wire(16)
add_key('none')
if wires[8] == 'yellow': cut_wire(11)
add_key('purple')
if cnt['purple'] == 5: cut_wire(11)
add_key('tiger')
if cnt['tiger'] == 16: cut_wire(11)
add_key('tan')
if cnt['tan'] == 6: cut_wire(19)
add_key('crimson')
if cnt['crimson'] >= 15: cut_wire(18)
add_key('wood')
if cnt['wood'] == 18: cut_wire(6)
add_key('none')
if wires[8] == 'brown': cut_wire(20)
add_key('penny')
if cnt['penny'] == 12: cut_wire(2)
add_key('none')
if wires[1] == 'grape': cut_wire(20)
add_key('none')
if wires[5] == 'silver': cut_wire(19)
add_key('none')
if wires[4] == 'caramel': cut_wire(11)
add_key('stone')
if cnt['stone'] == 2: cut_wire(15)
add_key('chocolate')
if cnt['chocolate'] == 7: cut_wire(20)
add_key('none')
if wires[18] == 'blush': cut_wire(6)
add_key('none')
if wires[8] == 'teal': cut_wire(3)
add_key('cobalt')
if cnt['cobalt'] == 15: cut_wire(5)
add_key('none')
if wires[3] == 'ruby': cut_wire(15)
add_key('gold')
if cnt['gold'] == 8: cut_wire(18)
add_key('orchid')
if cnt['orchid'] == 15: cut_wire(15)
add_key('butter')
if cnt['butter'] == 1: cut_wire(2)
add_key('rouge')
if cnt['rouge'] == 17: cut_wire(12)
add_key('none')
if wires[20] == 'peach': cut_wire(20)
add_key('none')
if wires[10] == 'coconut': cut_wire(5)
add_key('none')
if wires[20] == 'emerald': cut_wire(17)
add_key('plum')
if cnt['plum'] >= 7: cut_wire(19)
add_key('none')
if wires[4] == 'penny': cut_wire(11)
add_key('charcoal')
if cnt['charcoal'] == 1: cut_wire(19)
add_key('coconut')
if cnt['coconut'] == 6: cut_wire(14)
add_key('sand')
if cnt['sand'] == 10: cut_wire(9)
add_key('hazelnut')
if cnt['hazelnut'] == 3: cut_wire(18)
add_key('marmalade')
if cnt['marmalade'] == 20: cut_wire(18)
add_key('basil')
if cnt['basil'] >= 7: cut_wire(13)
add_key('pink')
if cnt['pink'] == 11: cut_wire(2)
add_key('honey')
if cnt['honey'] == 10: cut_wire(7)
add_key('none')
if wires[12] == 'blood': cut_wire(19)
add_key('amethyst')
if cnt['amethyst'] == 19: cut_wire(17)
add_key('amethyst')
if cnt['amethyst'] == 4: cut_wire(16)
add_key('fern')
if cnt['fern'] == 7: cut_wire(7)
add_key('charcoal')
if cnt['charcoal'] >= 15: cut_wire(1)
add_key('cobalt')
if cnt['cobalt'] == 2: cut_wire(18)
add_key('honey')
if cnt['honey'] == 12: cut_wire(17)
add_key('azure')
if cnt['azure'] == 5: cut_wire(15)
add_key('none')
if wires[5] == 'shamrock': cut_wire(5)
add_key('bone')
if cnt['bone'] == 17: cut_wire(12)
add_key('gray')
if cnt['gray'] == 9: cut_wire(14)
add_key('candy')
if cnt['candy'] == 13: cut_wire(20)
add_key('none')
if wires[3] == 'cloud': cut_wire(6)
add_key('cotton')
if cnt['cotton'] == 10: cut_wire(12)
add_key('rouge')
if cnt['rouge'] == 15: cut_wire(12)
add_key('rust')
if cnt['rust'] == 5: cut_wire(7)
add_key('none')
if wires[15] == 'lead': cut_wire(10)
add_key('banana')
if cnt['banana'] >= 7: cut_wire(2)
add_key('ash')
if cnt['ash'] == 19: cut_wire(16)
add_key('magenta')
if cnt['magenta'] == 1: cut_wire(20)
add_key('fern')
if cnt['fern'] == 6: cut_wire(7)
add_key('tiger')
if cnt['tiger'] == 14: cut_wire(20)
add_key('berry')
if cnt['berry'] == 12: cut_wire(9)
add_key('jade')
if cnt['jade'] >= 15: cut_wire(5)
add_key('pear')
if cnt['pear'] == 15: cut_wire(10)
add_key('none')
if wires[6] == 'pear': cut_wire(8)
add_key('none')
if wires[17] == 'violet': cut_wire(15)
add_key('none')
if wires[2] == 'pickle': cut_wire(11)
add_key('obsidian')
if cnt['obsidian'] == 15: cut_wire(2)
add_key('none')
if wires[11] == 'plum': cut_wire(10)
add_key('none')
if wires[1] == 'penny': cut_wire(6)
add_key('none')
if wires[9] == 'magenta': cut_wire(2)
add_key('granola')
if cnt['granola'] == 9: cut_wire(12)
add_key('none')
if wires[19] == 'carrot': cut_wire(8)
add_key('none')
if wires[9] == 'crepe': cut_wire(7)
add_key('none')
if wires[7] == 'iron': cut_wire(6)
add_key('none')
if wires[15] == 'iron': cut_wire(19)
add_key('wine')
if cnt['wine'] == 18: cut_wire(4)
add_key('none')
if wires[7] == 'chocolate': cut_wire(3)
add_key('peach')
if cnt['peach'] == 5: cut_wire(8)
add_key('sand')
if cnt['sand'] == 8: cut_wire(16)
add_key('wood')
if cnt['wood'] == 20: cut_wire(20)
add_key('none')
if wires[10] == 'tortilla': cut_wire(10)
add_key('none')
if wires[4] == 'ivory': cut_wire(2)
add_key('none')
if wires[7] == 'gray': cut_wire(13)
add_key('none')
if wires[15] == 'buttermilk': cut_wire(18)
add_key('orchid')
if cnt['orchid'] == 11: cut_wire(1)
add_key('shamrock')
if cnt['shamrock'] == 5: cut_wire(5)
add_key('none')
if wires[12] == 'frost': cut_wire(18)
add_key('orange')
if cnt['orange'] == 12: cut_wire(10)
add_key('purple')
if cnt['purple'] == 15: cut_wire(12)
add_key('fern')
if cnt['fern'] == 8: cut_wire(20)
add_key('none')
if wires[15] == 'white': cut_wire(12)
add_key('bone')
if cnt['bone'] == 15: cut_wire(15)
add_key('none')
if wires[10] == 'apricot': cut_wire(19)
add_key('stone')
if cnt['stone'] == 7: cut_wire(4)
add_key('none')
if wires[15] == 'shamrock': cut_wire(12)
add_key('crepe')
if cnt['crepe'] == 12: cut_wire(18)
add_key('red')
if cnt['red'] == 15: cut_wire(1)
add_key('sky')
if cnt['sky'] == 13: cut_wire(7)
add_key('pineapple')
if cnt['pineapple'] == 9: cut_wire(12)
add_key('cherry')
if cnt['cherry'] == 17: cut_wire(2)
add_key('brown')
if cnt['brown'] >= 14: cut_wire(16)
add_key('none')
if wires[1] == 'peach': cut_wire(2)
add_key('coconut')
if cnt['coconut'] == 13: cut_wire(19)
add_key('carrot')
if cnt['carrot'] == 1: cut_wire(20)
add_key('none')
if wires[5] == 'blood': cut_wire(18)
add_key('charcoal')
if cnt['charcoal'] == 4: cut_wire(12)
add_key('blood')
if cnt['blood'] == 19: cut_wire(11)
add_key('none')
if wires[19] == 'blue': cut_wire(15)
add_key('granola')
if cnt['granola'] == 18: cut_wire(15)
add_key('pickle')
if cnt['pickle'] == 19: cut_wire(1)
add_key('plum')
if cnt['plum'] == 13: cut_wire(3)
add_key('granola')
if cnt['granola'] == 9: cut_wire(6)
add_key('black')
if cnt['black'] == 19: cut_wire(19)
add_key('coconut')
if cnt['coconut'] == 14: cut_wire(18)
add_key('ruby')
if cnt['ruby'] == 12: cut_wire(7)
add_key('azure')
if cnt['azure'] == 20: cut_wire(7)
add_key('sage')
if cnt['sage'] == 15: cut_wire(3)
add_key('none')
if wires[12] == 'pickle': cut_wire(1)
add_key('lead')
if cnt['lead'] == 4: cut_wire(19)
add_key('azure')
if cnt['azure'] == 17: cut_wire(7)
add_key('none')
if wires[10] == 'sky': cut_wire(7)
add_key('teal')
if cnt['teal'] == 9: cut_wire(9)
add_key('pickle')
if cnt['pickle'] == 8: cut_wire(9)
add_key('rosewood')
if cnt['rosewood'] == 7: cut_wire(15)
add_key('shortbread')
if cnt['shortbread'] == 6: cut_wire(8)
add_key('none')
if wires[18] == 'brown': cut_wire(16)
add_key('seaweed')
if cnt['seaweed'] == 13: cut_wire(16)
add_key('bronze')
if cnt['bronze'] == 15: cut_wire(12)
add_key('none')
if wires[7] == 'bubblegum': cut_wire(20)
add_key('butter')
if cnt['butter'] == 13: cut_wire(15)
add_key('oyster')
if cnt['oyster'] == 2: cut_wire(14)
add_key('shamrock')
if cnt['shamrock'] >= 19: cut_wire(12)
add_key('none')
if wires[11] == 'apricot': cut_wire(7)
add_key('none')
if wires[19] == 'pearl': cut_wire(10)
add_key('none')
if wires[8] == 'iris': cut_wire(6)
add_key('none')
if wires[17] == 'shortbread': cut_wire(2)
add_key('none')
if wires[8] == 'lapis': cut_wire(14)
add_key('emerald')
if cnt['emerald'] == 19: cut_wire(18)
add_key('none')
if wires[2] == 'sandstone': cut_wire(14)
add_key('rosewood')
if cnt['rosewood'] == 18: cut_wire(6)
add_key('none')
if wires[12] == 'berry': cut_wire(13)
add_key('none')
if wires[14] == 'pear': cut_wire(2)
add_key('none')
if wires[10] == 'corn': cut_wire(4)
add_key('none')
if wires[11] == 'pickle': cut_wire(3)
add_key('navy')
if cnt['navy'] == 9: cut_wire(10)
add_key('chiffon')
if cnt['chiffon'] == 2: cut_wire(8)
add_key('none')
if wires[16] == 'hazelnut': cut_wire(8)
add_key('penny')
if cnt['penny'] == 19: cut_wire(12)
add_key('none')
if wires[11] == 'obsidian': cut_wire(15)
add_key('red')
if cnt['red'] == 19: cut_wire(7)
add_key('cherry')
if cnt['cherry'] == 1: cut_wire(16)
add_key('bone')
if cnt['bone'] == 8: cut_wire(20)
add_key('none')
if wires[6] == 'watermelon': cut_wire(9)
add_key('none')
if wires[10] == 'cobalt': cut_wire(9)
add_key('flint')
if cnt['flint'] == 5: cut_wire(4)
add_key('none')
if wires[9] == 'coconut': cut_wire(2)
add_key('none')
if wires[7] == 'iron': cut_wire(14)
add_key('none')
if wires[14] == 'coral': cut_wire(8)
add_key('silver')
if cnt['silver'] == 19: cut_wire(20)
add_key('none')
if wires[20] == 'rust': cut_wire(5)
add_key('emerald')
if cnt['emerald'] == 18: cut_wire(14)
add_key('latte')
if cnt['latte'] == 2: cut_wire(2)
add_key('none')
if wires[19] == 'tan': cut_wire(11)
add_key('none')
if wires[9] == 'basil': cut_wire(17)
add_key('red')
if cnt['red'] == 12: cut_wire(5)
add_key('plum')
if cnt['plum'] >= 15: cut_wire(18)
add_key('none')
if wires[19] == 'chiffon': cut_wire(15)
add_key('tiger')
if cnt['tiger'] == 18: cut_wire(8)
add_key('sky')
if cnt['sky'] == 15: cut_wire(5)
add_key('gray')
if cnt['gray'] == 20: cut_wire(12)
add_key('none')
if wires[12] == 'penny': cut_wire(11)
add_key('carrot')
if cnt['carrot'] == 20: cut_wire(18)
add_key('shortbread')
if cnt['shortbread'] == 5: cut_wire(19)
add_key('rouge')
if cnt['rouge'] == 4: cut_wire(6)
add_key('rust')
if cnt['rust'] == 10: cut_wire(14)
add_key('iris')
if cnt['iris'] == 2: cut_wire(15)
add_key('arctic')
if cnt['arctic'] == 12: cut_wire(15)
add_key('berry')
if cnt['berry'] == 8: cut_wire(2)
add_key('iris')
if cnt['iris'] == 2: cut_wire(14)
add_key('cloud')
if cnt['cloud'] == 1: cut_wire(5)
add_key('none')
if wires[10] == 'eggplant': cut_wire(16)
add_key('none')
if wires[18] == 'hickory': cut_wire(10)
add_key('none')
if wires[1] == 'crepe': cut_wire(20)
add_key('green')
if cnt['green'] >= 16: cut_wire(3)
add_key('blood')
if cnt['blood'] == 17: cut_wire(19)
add_key('lime')
if cnt['lime'] == 7: cut_wire(18)
add_key('bone')
if cnt['bone'] == 16: cut_wire(8)
add_key('ivory')
if cnt['ivory'] >= 16: cut_wire(9)
add_key('ash')
if cnt['ash'] >= 7: cut_wire(19)
add_key('watermelon')
if cnt['watermelon'] == 19: cut_wire(9)
add_key('silver')
if cnt['silver'] >= 13: cut_wire(7)
add_key('none')
if wires[1] == 'navy': cut_wire(18)
add_key('none')
if wires[4] == 'coral': cut_wire(10)
add_key('none')
if wires[12] == 'eggplant': cut_wire(11)
add_key('apricot')
if cnt['apricot'] == 5: cut_wire(20)
add_key('gray')
if cnt['gray'] >= 14: cut_wire(9)
add_key('none')
if wires[15] == 'tortilla': cut_wire(8)
add_key('pear')
if cnt['pear'] == 3: cut_wire(14)
add_key('chiffon')
if cnt['chiffon'] == 3: cut_wire(2)
add_key('watermelon')
if cnt['watermelon'] == 11: cut_wire(13)
add_key('none')
if wires[10] == 'crimson': cut_wire(13)
add_key('fawn')
if cnt['fawn'] == 12: cut_wire(5)
add_key('violet')
if cnt['violet'] >= 15: cut_wire(9)
add_key('arctic')
if cnt['arctic'] == 6: cut_wire(9)
add_key('none')
if wires[7] == 'shamrock': cut_wire(4)
add_key('watermelon')
if cnt['watermelon'] == 18: cut_wire(18)
add_key('teal')
if cnt['teal'] == 18: cut_wire(18)
add_key('watermelon')
if cnt['watermelon'] == 17: cut_wire(9)
add_key('rust')
if cnt['rust'] >= 13: cut_wire(7)
add_key('oyster')
if cnt['oyster'] == 1: cut_wire(4)
add_key('oyster')
if cnt['oyster'] == 4: cut_wire(19)
add_key('fern')
if cnt['fern'] == 13: cut_wire(8)
add_key('none')
if wires[11] == 'magenta': cut_wire(10)
add_key('pineapple')
if cnt['pineapple'] == 11: cut_wire(7)
add_key('scarlet')
if cnt['scarlet'] == 16: cut_wire(18)
add_key('none')
if wires[20] == 'sky': cut_wire(6)
add_key('lapis')
if cnt['lapis'] == 4: cut_wire(13)
add_key('none')
if wires[3] == 'arctic': cut_wire(3)
add_key('none')
if wires[8] == 'blue': cut_wire(1)
add_key('none')
if wires[16] == 'pear': cut_wire(11)
add_key('charcoal')
if cnt['charcoal'] == 4: cut_wire(13)
add_key('stone')
if cnt['stone'] == 9: cut_wire(18)
add_key('ruby')
if cnt['ruby'] == 10: cut_wire(3)
add_key('peach')
if cnt['peach'] == 17: cut_wire(17)
add_key('none')
if wires[12] == 'stone': cut_wire(9)
add_key('silver')
if cnt['silver'] == 3: cut_wire(16)
add_key('none')
if wires[3] == 'azure': cut_wire(20)
add_key('caramel')
if cnt['caramel'] == 15: cut_wire(13)
add_key('none')
if wires[16] == 'dijon': cut_wire(6)
add_key('watermelon')
if cnt['watermelon'] == 3: cut_wire(2)
add_key('teal')
if cnt['teal'] == 7: cut_wire(13)
add_key('none')
if wires[7] == 'peach': cut_wire(20)
add_key('none')
if wires[10] == 'blush': cut_wire(1)
add_key('granola')
if cnt['granola'] == 13: cut_wire(1)
add_key('none')
if wires[19] == 'coconut': cut_wire(1)
add_key('gold')
if cnt['gold'] == 4: cut_wire(1)
add_key('blue')
if cnt['blue'] >= 15: cut_wire(8)
add_key('navy')
if cnt['navy'] >= 10: cut_wire(4)
add_key('magenta')
if cnt['magenta'] == 7: cut_wire(6)
add_key('pink')
if cnt['pink'] == 10: cut_wire(4)
add_key('blush')
if cnt['blush'] == 12: cut_wire(5)
add_key('azure')
if cnt['azure'] == 13: cut_wire(2)
add_key('none')
if wires[16] == 'cobalt': cut_wire(20)
add_key('none')
if wires[17] == 'jade': cut_wire(17)
add_key('none')
if wires[19] == 'bone': cut_wire(19)
add_key('gold')
if cnt['gold'] == 6: cut_wire(11)
add_key('none')
if wires[18] == 'granola': cut_wire(12)
add_key('butter')
if cnt['butter'] == 7: cut_wire(9)
add_key('none')
if wires[13] == 'stone': cut_wire(16)
add_key('none')
if wires[11] == 'green': cut_wire(11)
add_key('emerald')
if cnt['emerald'] == 9: cut_wire(11)
add_key('basil')
if cnt['basil'] == 3: cut_wire(8)
add_key('none')
if wires[16] == 'ruby': cut_wire(9)
add_key('none')
if wires[18] == 'white': cut_wire(7)
add_key('none')
if wires[14] == 'seaweed': cut_wire(2)
add_key('cobalt')
if cnt['cobalt'] == 1: cut_wire(7)
add_key('sky')
if cnt['sky'] == 17: cut_wire(17)
add_key('bubblegum')
if cnt['bubblegum'] >= 15: cut_wire(3)
add_key('none')
if wires[13] == 'arctic': cut_wire(3)
add_key('none')
if wires[19] == 'pear': cut_wire(17)
add_key('cherry')
if cnt['cherry'] == 12: cut_wire(5)
add_key('none')
if wires[10] == 'hazelnut': cut_wire(9)
add_key('none')
if wires[9] == 'tortilla': cut_wire(10)
add_key('none')
if wires[12] == 'pineapple': cut_wire(15)
add_key('frost')
if cnt['frost'] == 4: cut_wire(19)
add_key('shortbread')
if cnt['shortbread'] == 20: cut_wire(17)
add_key('bronze')
if cnt['bronze'] >= 9: cut_wire(11)
add_key('none')
if wires[9] == 'ivory': cut_wire(13)
add_key('none')
if wires[8] == 'pearl': cut_wire(7)
add_key('none')
if wires[13] == 'scarlet': cut_wire(11)
add_key('cotton')
if cnt['cotton'] == 7: cut_wire(12)
add_key('none')
if wires[3] == 'seaweed': cut_wire(6)
add_key('none')
if wires[20] == 'iron': cut_wire(9)
add_key('banana')
if cnt['banana'] == 7: cut_wire(1)
add_key('none')
if wires[19] == 'berry': cut_wire(14)
add_key('teal')
if cnt['teal'] == 1: cut_wire(1)
add_key('none')
if wires[5] == 'coral': cut_wire(5)
add_key('cotton')
if cnt['cotton'] == 4: cut_wire(13)
add_key('stone')
if cnt['stone'] == 9: cut_wire(5)
add_key('teal')
if cnt['teal'] == 3: cut_wire(1)
add_key('crimson')
if cnt['crimson'] == 1: cut_wire(15)
add_key('none')
if wires[8] == 'grape': cut_wire(5)
add_key('none')
if wires[6] == 'hickory': cut_wire(14)
add_key('corn')
if cnt['corn'] == 18: cut_wire(14)
add_key('wine')
if cnt['wine'] >= 14: cut_wire(6)
add_key('cotton')
if cnt['cotton'] == 2: cut_wire(3)
add_key('none')
if wires[4] == 'iris': cut_wire(10)
add_key('coconut')
if cnt['coconut'] == 5: cut_wire(20)
add_key('honey')
if cnt['honey'] == 2: cut_wire(10)
add_key('granola')
if cnt['granola'] == 2: cut_wire(3)
add_key('none')
if wires[3] == 'jade': cut_wire(7)
add_key('sky')
if cnt['sky'] == 4: cut_wire(6)
add_key('none')
if wires[1] == 'caramel': cut_wire(4)
add_key('none')
if wires[19] == 'coral': cut_wire(9)
add_key('latte')
if cnt['latte'] == 8: cut_wire(9)
add_key('azure')
if cnt['azure'] == 7: cut_wire(19)
add_key('none')
if wires[5] == 'yellow': cut_wire(15)
add_key('pineapple')
if cnt['pineapple'] >= 15: cut_wire(17)
add_key('none')
if wires[1] == 'navy': cut_wire(1)
add_key('peach')
if cnt['peach'] == 10: cut_wire(1)
add_key('none')
if wires[1] == 'coconut': cut_wire(14)
add_key('none')
if wires[13] == 'apricot': cut_wire(16)
add_key('black')
if cnt['black'] == 12: cut_wire(6)
add_key('azure')
if cnt['azure'] == 12: cut_wire(17)
add_key('azure')
if cnt['azure'] == 11: cut_wire(9)
add_key('ash')
if cnt['ash'] == 8: cut_wire(20)
add_key('orchid')
if cnt['orchid'] == 19: cut_wire(5)
add_key('lapis')
if cnt['lapis'] == 6: cut_wire(4)
add_key('none')
if wires[7] == 'penny': cut_wire(2)
add_key('apricot')
if cnt['apricot'] == 20: cut_wire(3)
add_key('latte')
if cnt['latte'] == 6: cut_wire(16)
add_key('butter')
if cnt['butter'] >= 14: cut_wire(6)
add_key('sky')
if cnt['sky'] == 20: cut_wire(3)
add_key('none')
if wires[3] == 'seaweed': cut_wire(12)
add_key('none')
if wires[6] == 'magenta': cut_wire(4)
add_key('apricot')
if cnt['apricot'] == 13: cut_wire(19)
add_key('lead')
if cnt['lead'] >= 9: cut_wire(6)
add_key('green')
if cnt['green'] == 19: cut_wire(5)
add_key('tan')
if cnt['tan'] == 7: cut_wire(15)
add_key('none')
if wires[12] == 'silver': cut_wire(8)
add_key('none')
if wires[3] == 'penny': cut_wire(2)
add_key('none')
if wires[20] == 'porcelain': cut_wire(18)
add_key('none')
if wires[16] == 'chocolate': cut_wire(19)
add_key('none')
if wires[10] == 'fawn': cut_wire(7)
add_key('marmalade')
if cnt['marmalade'] == 14: cut_wire(20)
add_key('none')
if wires[14] == 'cotton': cut_wire(6)
add_key('none')
if wires[11] == 'emerald': cut_wire(13)
add_key('tan')
if cnt['tan'] == 9: cut_wire(14)
add_key('none')
if wires[16] == 'white': cut_wire(11)
add_key('fawn')
if cnt['fawn'] == 19: cut_wire(15)
add_key('butter')
if cnt['butter'] == 3: cut_wire(19)
add_key('squash')
if cnt['squash'] == 13: cut_wire(11)
add_key('carrot')
if cnt['carrot'] == 6: cut_wire(18)
add_key('ruby')
if cnt['ruby'] == 17: cut_wire(5)
add_key('caramel')
if cnt['caramel'] == 15: cut_wire(19)
add_key('none')
if wires[19] == 'pineapple': cut_wire(2)
add_key('marmalade')
if cnt['marmalade'] == 2: cut_wire(2)
add_key('none')
if wires[12] == 'marigold': cut_wire(16)
add_key('sage')
if cnt['sage'] == 17: cut_wire(18)
add_key('grape')
if cnt['grape'] == 13: cut_wire(17)
add_key('granola')
if cnt['granola'] == 1: cut_wire(6)
add_key('teal')
if cnt['teal'] == 19: cut_wire(10)
add_key('none')
if wires[18] == 'purple': cut_wire(10)
add_key('sandstone')
if cnt['sandstone'] == 4: cut_wire(20)
add_key('none')
if wires[3] == 'penny': cut_wire(10)
add_key('orange')
if cnt['orange'] == 5: cut_wire(19)
add_key('coral')
if cnt['coral'] == 10: cut_wire(19)
add_key('sandstone')
if cnt['sandstone'] >= 16: cut_wire(2)
add_key('purple')
if cnt['purple'] == 10: cut_wire(17)
add_key('lime')
if cnt['lime'] >= 14: cut_wire(7)
add_key('lime')
if cnt['lime'] == 6: cut_wire(19)
add_key('shamrock')
if cnt['shamrock'] == 5: cut_wire(13)
add_key('blood')
if cnt['blood'] == 13: cut_wire(8)
add_key('granola')
if cnt['granola'] >= 18: cut_wire(19)
add_key('blood')
if cnt['blood'] == 7: cut_wire(16)
add_key('banana')
if cnt['banana'] >= 12: cut_wire(9)
add_key('none')
if wires[8] == 'jade': cut_wire(12)
add_key('cherry')
if cnt['cherry'] == 7: cut_wire(15)
add_key('flint')
if cnt['flint'] == 18: cut_wire(1)
add_key('none')
if wires[5] == 'cherry': cut_wire(9)
add_key('lemon')
if cnt['lemon'] >= 17: cut_wire(4)
add_key('chocolate')
if cnt['chocolate'] == 5: cut_wire(13)
add_key('bronze')
if cnt['bronze'] == 6: cut_wire(5)
add_key('magenta')
if cnt['magenta'] == 18: cut_wire(4)
add_key('none')
if wires[9] == 'bronze': cut_wire(10)
add_key('none')
if wires[4] == 'brown': cut_wire(7)
add_key('none')
if wires[4] == 'watermelon': cut_wire(7)
add_key('none')
if wires[17] == 'carrot': cut_wire(16)
add_key('berry')
if cnt['berry'] >= 11: cut_wire(19)
add_key('none')
if wires[15] == 'bone': cut_wire(4)
add_key('coconut')
if cnt['coconut'] == 4: cut_wire(1)
add_key('granola')
if cnt['granola'] == 18: cut_wire(11)
add_key('none')
if wires[20] == 'pink': cut_wire(13)
add_key('none')
if wires[7] == 'flint': cut_wire(4)
add_key('cobalt')
if cnt['cobalt'] == 19: cut_wire(16)
add_key('berry')
if cnt['berry'] == 1: cut_wire(2)
add_key('none')
if wires[12] == 'ash': cut_wire(7)
add_key('carrot')
if cnt['carrot'] == 16: cut_wire(7)
add_key('none')
if wires[20] == 'rosewood': cut_wire(8)
add_key('none')
if wires[19] == 'butter': cut_wire(8)
add_key('none')
if wires[17] == 'granola': cut_wire(19)
add_key('bubblegum')
if cnt['bubblegum'] == 15: cut_wire(18)
add_key('jade')
if cnt['jade'] == 14: cut_wire(4)
add_key('black')
if cnt['black'] == 8: cut_wire(12)
add_key('silver')
if cnt['silver'] == 6: cut_wire(9)
add_key('hazelnut')
if cnt['hazelnut'] == 20: cut_wire(12)
add_key('wine')
if cnt['wine'] == 19: cut_wire(11)
add_key('none')
if wires[12] == 'pink': cut_wire(5)
add_key('none')
if wires[5] == 'teal': cut_wire(7)
add_key('chiffon')
if cnt['chiffon'] == 8: cut_wire(5)
add_key('butter')
if cnt['butter'] == 8: cut_wire(8)
add_key('honey')
if cnt['honey'] == 8: cut_wire(17)
add_key('none')
if wires[8] == 'wine': cut_wire(15)
add_key('bubblegum')
if cnt['bubblegum'] >= 7: cut_wire(14)
add_key('stone')
if cnt['stone'] == 11: cut_wire(20)
add_key('none')
if wires[15] == 'ruby': cut_wire(7)
add_key('penny')
if cnt['penny'] == 6: cut_wire(11)
add_key('arctic')
if cnt['arctic'] == 15: cut_wire(6)
add_key('hickory')
if cnt['hickory'] == 14: cut_wire(1)
add_key('none')
if wires[11] == 'arctic': cut_wire(16)
add_key('red')
if cnt['red'] == 3: cut_wire(12)
add_key('none')
if wires[16] == 'pear': cut_wire(15)
add_key('none')
if wires[2] == 'cloud': cut_wire(14)
add_key('rose')
if cnt['rose'] == 19: cut_wire(10)
add_key('marmalade')
if cnt['marmalade'] == 5: cut_wire(8)
add_key('daisy')
if cnt['daisy'] == 18: cut_wire(1)
add_key('none')
if wires[9] == 'corn': cut_wire(13)
add_key('pearl')
if cnt['pearl'] == 13: cut_wire(13)
add_key('none')
if wires[18] == 'obsidian': cut_wire(20)
add_key('silver')
if cnt['silver'] == 10: cut_wire(17)
add_key('shortbread')
if cnt['shortbread'] == 12: cut_wire(13)
add_key('none')
if wires[16] == 'yellow': cut_wire(9)
add_key('none')
if wires[2] == 'charcoal': cut_wire(18)
add_key('ash')
if cnt['ash'] == 15: cut_wire(8)
add_key('none')
if wires[3] == 'shamrock': cut_wire(8)
add_key('sandstone')
if cnt['sandstone'] == 13: cut_wire(5)
add_key('black')
if cnt['black'] == 8: cut_wire(19)
add_key('none')
if wires[20] == 'wood': cut_wire(7)
add_key('pearl')
if cnt['pearl'] == 18: cut_wire(19)
add_key('rouge')
if cnt['rouge'] == 20: cut_wire(1)
add_key('bronze')
if cnt['bronze'] == 2: cut_wire(9)
add_key('azure')
if cnt['azure'] == 15: cut_wire(10)
add_key('none')
if wires[19] == 'candy': cut_wire(8)
add_key('macaroon')
if cnt['macaroon'] == 14: cut_wire(16)
add_key('none')
if wires[20] == 'pear': cut_wire(10)
add_key('coral')
if cnt['coral'] == 4: cut_wire(8)
add_key('none')
if wires[19] == 'scarlet': cut_wire(5)
add_key('orchid')
if cnt['orchid'] == 19: cut_wire(15)
add_key('plum')
if cnt['plum'] == 16: cut_wire(2)
add_key('charcoal')
if cnt['charcoal'] == 5: cut_wire(12)
add_key('latte')
if cnt['latte'] == 19: cut_wire(12)
add_key('wood')
if cnt['wood'] == 5: cut_wire(2)
add_key('orchid')
if cnt['orchid'] == 5: cut_wire(7)
add_key('none')
if wires[17] == 'corn': cut_wire(10)
add_key('bone')
if cnt['bone'] == 14: cut_wire(10)
add_key('bubblegum')
if cnt['bubblegum'] >= 11: cut_wire(16)
add_key('fire')
if cnt['fire'] == 18: cut_wire(17)
add_key('white')
if cnt['white'] == 14: cut_wire(1)
add_key('cherry')
if cnt['cherry'] == 2: cut_wire(16)
add_key('none')
if wires[12] == 'cotton': cut_wire(16)
add_key('none')
if wires[10] == 'carrot': cut_wire(17)
add_key('none')
if wires[14] == 'banana': cut_wire(8)
add_key('fire')
if cnt['fire'] == 7: cut_wire(8)
add_key('none')
if wires[2] == 'blood': cut_wire(2)
add_key('none')
if wires[13] == 'lemon': cut_wire(3)
add_key('plum')
if cnt['plum'] == 16: cut_wire(18)
add_key('none')
if wires[20] == 'cotton': cut_wire(20)
add_key('black')
if cnt['black'] >= 13: cut_wire(6)
add_key('shamrock')
if cnt['shamrock'] == 18: cut_wire(20)
add_key('lime')
if cnt['lime'] >= 13: cut_wire(12)
add_key('none')
if wires[3] == 'apricot': cut_wire(17)
add_key('magenta')
if cnt['magenta'] == 20: cut_wire(11)
add_key('azure')
if cnt['azure'] == 6: cut_wire(2)
add_key('latte')
if cnt['latte'] == 11: cut_wire(19)
add_key('none')
if wires[5] == 'coconut': cut_wire(20)
add_key('ivory')
if cnt['ivory'] == 5: cut_wire(6)
add_key('bubblegum')
if cnt['bubblegum'] == 4: cut_wire(20)
add_key('tan')
if cnt['tan'] == 4: cut_wire(13)
add_key('fawn')
if cnt['fawn'] == 3: cut_wire(18)
add_key('gold')
if cnt['gold'] >= 9: cut_wire(10)
add_key('blue')
if cnt['blue'] == 10: cut_wire(1)
add_key('macaroon')
if cnt['macaroon'] == 4: cut_wire(1)
add_key('none')
if wires[7] == 'magenta': cut_wire(14)
add_key('candy')
if cnt['candy'] == 17: cut_wire(17)
add_key('none')
if wires[10] == 'daisy': cut_wire(3)
add_key('chocolate')
if cnt['chocolate'] == 8: cut_wire(3)
add_key('none')
if wires[16] == 'tan': cut_wire(12)
add_key('tan')
if cnt['tan'] == 1: cut_wire(3)
add_key('none')
if wires[15] == 'bronze': cut_wire(18)
add_key('daisy')
if cnt['daisy'] == 18: cut_wire(5)
add_key('hazelnut')
if cnt['hazelnut'] == 13: cut_wire(12)
add_key('none')
if wires[12] == 'charcoal': cut_wire(12)
add_key('orchid')
if cnt['orchid'] == 16: cut_wire(9)
add_key('none')
if wires[10] == 'cotton': cut_wire(17)
add_key('carrot')
if cnt['carrot'] == 17: cut_wire(6)
add_key('sky')
if cnt['sky'] == 13: cut_wire(9)
add_key('none')
if wires[20] == 'tortilla': cut_wire(13)
add_key('shamrock')
if cnt['shamrock'] == 16: cut_wire(3)
add_key('none')
if wires[8] == 'lapis': cut_wire(6)
add_key('none')
if wires[18] == 'cherry': cut_wire(10)
add_key('wood')
if cnt['wood'] == 10: cut_wire(1)
add_key('hazelnut')
if cnt['hazelnut'] == 4: cut_wire(5)
add_key('tan')
if cnt['tan'] == 12: cut_wire(9)
add_key('corn')
if cnt['corn'] == 12: cut_wire(8)
add_key('iris')
if cnt['iris'] == 3: cut_wire(20)
add_key('jade')
if cnt['jade'] == 5: cut_wire(3)
add_key('none')
if wires[13] == 'plum': cut_wire(18)
add_key('none')
if wires[13] == 'brick': cut_wire(11)
add_key('banana')
if cnt['banana'] == 3: cut_wire(8)
add_key('none')
if wires[17] == 'cloud': cut_wire(2)
add_key('coral')
if cnt['coral'] == 19: cut_wire(13)
add_key('plum')
if cnt['plum'] == 16: cut_wire(15)
add_key('daisy')
if cnt['daisy'] >= 8: cut_wire(19)
add_key('rouge')
if cnt['rouge'] == 16: cut_wire(18)
add_key('lemon')
if cnt['lemon'] == 19: cut_wire(2)
add_key('red')
if cnt['red'] == 10: cut_wire(11)
add_key('sky')
if cnt['sky'] == 6: cut_wire(4)
add_key('red')
if cnt['red'] == 8: cut_wire(8)
add_key('pearl')
if cnt['pearl'] == 7: cut_wire(1)
add_key('none')
if wires[18] == 'charcoal': cut_wire(20)
add_key('brown')
if cnt['brown'] == 9: cut_wire(20)
add_key('caramel')
if cnt['caramel'] == 11: cut_wire(7)
add_key('none')
if wires[9] == 'azure': cut_wire(8)
add_key('eggplant')
if cnt['eggplant'] == 16: cut_wire(7)
add_key('none')
if wires[10] == 'oyster': cut_wire(1)
add_key('magenta')
if cnt['magenta'] == 6: cut_wire(10)
add_key('none')
if wires[18] == 'shamrock': cut_wire(6)
add_key('black')
if cnt['black'] == 13: cut_wire(19)
add_key('none')
if wires[11] == 'fire': cut_wire(12)
add_key('plum')
if cnt['plum'] == 18: cut_wire(17)
add_key('charcoal')
if cnt['charcoal'] >= 12: cut_wire(10)
add_key('granola')
if cnt['granola'] == 1: cut_wire(14)
add_key('none')
if wires[2] == 'honey': cut_wire(20)
add_key('stone')
if cnt['stone'] == 5: cut_wire(9)
add_key('navy')
if cnt['navy'] >= 7: cut_wire(6)
add_key('none')
if wires[2] == 'dijon': cut_wire(4)
add_key('cherry')
if cnt['cherry'] == 20: cut_wire(18)
add_key('ash')
if cnt['ash'] == 17: cut_wire(19)
add_key('none')
if wires[1] == 'pear': cut_wire(19)
add_key('white')
if cnt['white'] == 18: cut_wire(9)
add_key('scarlet')
if cnt['scarlet'] >= 19: cut_wire(10)
add_key('none')
if wires[8] == 'porcelain': cut_wire(18)
add_key('yellow')
if cnt['yellow'] == 2: cut_wire(10)
add_key('none')
if wires[13] == 'emerald': cut_wire(20)
add_key('none')
if wires[1] == 'azure': cut_wire(12)
add_key('none')
if wires[3] == 'scarlet': cut_wire(12)
add_key('cobalt')
if cnt['cobalt'] == 9: cut_wire(1)
add_key('arctic')
if cnt['arctic'] == 4: cut_wire(19)
add_key('arctic')
if cnt['arctic'] == 17: cut_wire(13)
add_key('wood')
if cnt['wood'] == 5: cut_wire(19)
add_key('none')
if wires[19] == 'berry': cut_wire(1)
add_key('none')
if wires[1] == 'ash': cut_wire(1)
add_key('sandstone')
if cnt['sandstone'] == 6: cut_wire(19)
add_key('flint')
if cnt['flint'] == 14: cut_wire(18)
add_key('crimson')
if cnt['crimson'] == 14: cut_wire(19)
add_key('none')
if wires[6] == 'oyster': cut_wire(20)
add_key('none')
if wires[4] == 'emerald': cut_wire(13)
add_key('stone')
if cnt['stone'] == 13: cut_wire(15)
add_key('pear')
if cnt['pear'] == 7: cut_wire(3)
add_key('none')
if wires[1] == 'pickle': cut_wire(20)
add_key('none')
if wires[7] == 'lead': cut_wire(16)
add_key('none')
if wires[6] == 'wine': cut_wire(14)
add_key('bone')
if cnt['bone'] == 15: cut_wire(8)
add_key('black')
if cnt['black'] == 4: cut_wire(17)
add_key('none')
if wires[3] == 'arctic': cut_wire(1)
add_key('none')
if wires[1] == 'iron': cut_wire(16)
add_key('none')
if wires[3] == 'tan': cut_wire(15)
add_key('none')
if wires[8] == 'purple': cut_wire(3)
add_key('candy')
if cnt['candy'] == 16: cut_wire(15)
add_key('none')
if wires[2] == 'grape': cut_wire(13)
add_key('eggplant')
if cnt['eggplant'] == 9: cut_wire(20)
add_key('coral')
if cnt['coral'] == 4: cut_wire(18)
add_key('none')
if wires[9] == 'seaweed': cut_wire(2)
add_key('none')
if wires[1] == 'squash': cut_wire(16)
add_key('none')
if wires[13] == 'apricot': cut_wire(10)
add_key('none')
if wires[8] == 'fawn': cut_wire(17)
add_key('none')
if wires[15] == 'penny': cut_wire(15)
add_key('none')
if wires[3] == 'rose': cut_wire(19)
add_key('none')
if wires[11] == 'tiger': cut_wire(11)
add_key('yellow')
if cnt['yellow'] == 3: cut_wire(19)
add_key('rose')
if cnt['rose'] == 14: cut_wire(6)
add_key('honey')
if cnt['honey'] == 7: cut_wire(13)
add_key('blue')
if cnt['blue'] == 12: cut_wire(19)
add_key('green')
if cnt['green'] >= 11: cut_wire(5)
add_key('none')
if wires[9] == 'shamrock': cut_wire(20)
add_key('none')
if wires[10] == 'rosewood': cut_wire(6)
add_key('banana')
if cnt['banana'] == 6: cut_wire(19)
add_key('none')
if wires[19] == 'teal': cut_wire(10)
add_key('none')
if wires[20] == 'corn': cut_wire(6)
add_key('bronze')
if cnt['bronze'] == 10: cut_wire(19)
add_key('pear')
if cnt['pear'] == 13: cut_wire(12)
add_key('white')
if cnt['white'] == 6: cut_wire(5)
add_key('none')
if wires[9] == 'caramel': cut_wire(18)
add_key('none')
if wires[18] == 'corn': cut_wire(13)
add_key('none')
if wires[19] == 'plum': cut_wire(18)
add_key('banana')
if cnt['banana'] >= 16: cut_wire(20)
add_key('none')
if wires[7] == 'frost': cut_wire(18)
add_key('ash')
if cnt['ash'] == 5: cut_wire(8)
add_key('bronze')
if cnt['bronze'] == 4: cut_wire(2)
add_key('cherry')
if cnt['cherry'] >= 14: cut_wire(7)
add_key('none')
if wires[6] == 'cobalt': cut_wire(14)
add_key('obsidian')
if cnt['obsidian'] == 16: cut_wire(15)
add_key('none')
if wires[11] == 'pickle': cut_wire(14)
add_key('blue')
if cnt['blue'] == 7: cut_wire(7)
add_key('ivory')
if cnt['ivory'] == 2: cut_wire(15)
add_key('none')
if wires[10] == 'red': cut_wire(6)
add_key('none')
if wires[4] == 'bubblegum': cut_wire(13)
add_key('none')
if wires[5] == 'penny': cut_wire(13)
add_key('macaroon')
if cnt['macaroon'] == 8: cut_wire(20)
add_key('peach')
if cnt['peach'] == 10: cut_wire(9)
add_key('amethyst')
if cnt['amethyst'] == 3: cut_wire(15)
add_key('none')
if wires[4] == 'seaweed': cut_wire(3)
add_key('sand')
if cnt['sand'] == 8: cut_wire(3)
add_key('none')
if wires[19] == 'wine': cut_wire(5)
add_key('fern')
if cnt['fern'] == 3: cut_wire(18)
add_key('bubblegum')
if cnt['bubblegum'] == 19: cut_wire(18)
add_key('none')
if wires[6] == 'shortbread': cut_wire(9)
add_key('coffee')
if cnt['coffee'] >= 19: cut_wire(13)
add_key('bone')
if cnt['bone'] == 16: cut_wire(15)
add_key('none')
if wires[9] == 'pearl': cut_wire(13)
add_key('grape')
if cnt['grape'] == 8: cut_wire(20)
add_key('none')
if wires[11] == 'violet': cut_wire(18)
add_key('pineapple')
if cnt['pineapple'] == 4: cut_wire(3)
add_key('tan')
if cnt['tan'] == 20: cut_wire(19)
add_key('none')
if wires[8] == 'gold': cut_wire(17)
add_key('none')
if wires[16] == 'tiger': cut_wire(11)
add_key('none')
if wires[13] == 'bone': cut_wire(17)
add_key('squash')
if cnt['squash'] == 5: cut_wire(19)
add_key('none')
if wires[12] == 'magenta': cut_wire(8)
add_key('orchid')
if cnt['orchid'] == 13: cut_wire(20)
add_key('none')
if wires[17] == 'ivory': cut_wire(11)
add_key('none')
if wires[16] == 'pear': cut_wire(5)
add_key('basil')
if cnt['basil'] == 6: cut_wire(2)
add_key('charcoal')
if cnt['charcoal'] >= 9: cut_wire(8)
add_key('none')
if wires[5] == 'banana': cut_wire(5)
add_key('none')
if wires[19] == 'carrot': cut_wire(1)
add_key('crimson')
if cnt['crimson'] == 19: cut_wire(4)
add_key('none')
if wires[18] == 'marmalade': cut_wire(17)
add_key('iron')
if cnt['iron'] == 19: cut_wire(5)
add_key('none')
if wires[9] == 'pink': cut_wire(20)
add_key('cobalt')
if cnt['cobalt'] == 15: cut_wire(5)
add_key('fire')
if cnt['fire'] >= 14: cut_wire(2)
add_key('teal')
if cnt['teal'] == 13: cut_wire(8)
add_key('none')
if wires[2] == 'cherry': cut_wire(2)
add_key('none')
if wires[12] == 'green': cut_wire(18)
add_key('white')
if cnt['white'] >= 14: cut_wire(19)
add_key('red')
if cnt['red'] == 18: cut_wire(16)
add_key('none')
if wires[20] == 'rose': cut_wire(20)
add_key('none')
if wires[1] == 'rust': cut_wire(9)
add_key('amethyst')
if cnt['amethyst'] == 15: cut_wire(11)
add_key('coffee')
if cnt['coffee'] == 10: cut_wire(2)
add_key('green')
if cnt['green'] == 3: cut_wire(18)
add_key('orchid')
if cnt['orchid'] == 2: cut_wire(2)
add_key('none')
if wires[3] == 'violet': cut_wire(15)
add_key('gold')
if cnt['gold'] == 2: cut_wire(16)
add_key('none')
if wires[18] == 'ivory': cut_wire(17)
add_key('penny')
if cnt['penny'] == 15: cut_wire(19)
add_key('none')
if wires[1] == 'corn': cut_wire(5)
add_key('lemon')
if cnt['lemon'] >= 19: cut_wire(8)
add_key('wood')
if cnt['wood'] == 9: cut_wire(2)
add_key('none')
if wires[1] == 'shortbread': cut_wire(2)
add_key('seaweed')
if cnt['seaweed'] == 11: cut_wire(14)
add_key('none')
if wires[19] == 'cotton': cut_wire(9)
add_key('fern')
if cnt['fern'] == 20: cut_wire(20)
add_key('charcoal')
if cnt['charcoal'] == 20: cut_wire(1)
add_key('rose')
if cnt['rose'] == 15: cut_wire(6)
add_key('none')
if wires[7] == 'arctic': cut_wire(15)
add_key('obsidian')
if cnt['obsidian'] == 20: cut_wire(7)
add_key('none')
if wires[7] == 'candy': cut_wire(4)
add_key('granola')
if cnt['granola'] == 20: cut_wire(20)
add_key('brown')
if cnt['brown'] >= 15: cut_wire(15)
add_key('oyster')
if cnt['oyster'] == 6: cut_wire(14)
add_key('none')
if wires[1] == 'flint': cut_wire(11)
add_key('tan')
if cnt['tan'] == 13: cut_wire(2)
add_key('granola')
if cnt['granola'] == 14: cut_wire(16)
add_key('squash')
if cnt['squash'] == 7: cut_wire(13)
add_key('none')
if wires[8] == 'blood': cut_wire(3)
add_key('none')
if wires[17] == 'dijon': cut_wire(16)
add_key('none')
if wires[2] == 'buttermilk': cut_wire(6)
add_key('grape')
if cnt['grape'] >= 16: cut_wire(8)
add_key('sand')
if cnt['sand'] == 18: cut_wire(11)
add_key('lemon')
if cnt['lemon'] == 2: cut_wire(17)
add_key('rosewood')
if cnt['rosewood'] == 3: cut_wire(15)
add_key('none')
if wires[12] == 'chocolate': cut_wire(14)
add_key('gold')
if cnt['gold'] == 7: cut_wire(6)
add_key('none')
if wires[12] == 'bubblegum': cut_wire(6)
add_key('eggplant')
if cnt['eggplant'] == 4: cut_wire(7)
add_key('crimson')
if cnt['crimson'] == 20: cut_wire(9)
add_key('yellow')
if cnt['yellow'] == 11: cut_wire(20)
add_key('coconut')
if cnt['coconut'] == 13: cut_wire(15)
add_key('pickle')
if cnt['pickle'] >= 18: cut_wire(19)
add_key('ruby')
if cnt['ruby'] == 9: cut_wire(4)
add_key('none')
if wires[2] == 'green': cut_wire(7)
add_key('none')
if wires[6] == 'candy': cut_wire(1)
add_key('none')
if wires[10] == 'bronze': cut_wire(1)
add_key('lapis')
if cnt['lapis'] >= 11: cut_wire(12)
add_key('frost')
if cnt['frost'] >= 17: cut_wire(18)
add_key('green')
if cnt['green'] == 16: cut_wire(13)
add_key('crimson')
if cnt['crimson'] == 5: cut_wire(8)
add_key('none')
if wires[10] == 'bronze': cut_wire(11)
add_key('marmalade')
if cnt['marmalade'] == 12: cut_wire(2)
add_key('sage')
if cnt['sage'] >= 10: cut_wire(1)
add_key('none')
if wires[13] == 'watermelon': cut_wire(17)
add_key('none')
if wires[5] == 'purple': cut_wire(16)
add_key('cotton')
if cnt['cotton'] == 11: cut_wire(1)
add_key('ash')
if cnt['ash'] >= 19: cut_wire(19)
add_key('none')
if wires[20] == 'frost': cut_wire(3)
add_key('wine')
if cnt['wine'] == 9: cut_wire(20)
add_key('banana')
if cnt['banana'] == 15: cut_wire(19)
add_key('violet')
if cnt['violet'] >= 14: cut_wire(2)
add_key('azure')
if cnt['azure'] == 8: cut_wire(2)
add_key('none')
if wires[8] == 'purple': cut_wire(15)
add_key('none')
if wires[14] == 'dijon': cut_wire(13)
add_key('ivory')
if cnt['ivory'] == 10: cut_wire(7)
add_key('none')
if wires[6] == 'rose': cut_wire(1)
add_key('none')
if wires[14] == 'apricot': cut_wire(13)
add_key('latte')
if cnt['latte'] == 14: cut_wire(10)
add_key('magenta')
if cnt['magenta'] == 3: cut_wire(7)
add_key('none')
if wires[3] == 'stone': cut_wire(5)
add_key('none')
if wires[1] == 'orchid': cut_wire(1)
add_key('none')
if wires[19] == 'sky': cut_wire(20)
add_key('basil')
if cnt['basil'] == 19: cut_wire(17)
add_key('fire')
if cnt['fire'] == 10: cut_wire(17)
add_key('none')
if wires[17] == 'violet': cut_wire(5)
add_key('none')
if wires[1] == 'orange': cut_wire(10)
add_key('berry')
if cnt['berry'] == 7: cut_wire(10)
add_key('marigold')
if cnt['marigold'] == 8: cut_wire(19)
add_key('lapis')
if cnt['lapis'] == 10: cut_wire(7)
add_key('chiffon')
if cnt['chiffon'] == 2: cut_wire(18)
add_key('none')
if wires[13] == 'buttermilk': cut_wire(20)
add_key('none')
if wires[5] == 'candy': cut_wire(5)
add_key('coral')
if cnt['coral'] == 18: cut_wire(20)
add_key('none')
if wires[6] == 'tan': cut_wire(20)
add_key('pearl')
if cnt['pearl'] == 14: cut_wire(12)
add_key('coffee')
if cnt['coffee'] == 1: cut_wire(8)
add_key('rose')
if cnt['rose'] == 5: cut_wire(13)
add_key('none')
if wires[5] == 'macaroon': cut_wire(16)
add_key('none')
if wires[2] == 'bone': cut_wire(11)
add_key('none')
if wires[3] == 'cobalt': cut_wire(15)
add_key('rouge')
if cnt['rouge'] == 12: cut_wire(13)
add_key('none')
if wires[20] == 'hickory': cut_wire(13)
add_key('marmalade')
if cnt['marmalade'] == 1: cut_wire(10)
add_key('latte')
if cnt['latte'] == 15: cut_wire(20)
add_key('none')
if wires[9] == 'emerald': cut_wire(2)
add_key('none')
if wires[4] == 'blue': cut_wire(4)
add_key('white')
if cnt['white'] == 19: cut_wire(4)
add_key('none')
if wires[7] == 'obsidian': cut_wire(3)
add_key('pink')
if cnt['pink'] == 17: cut_wire(6)
add_key('none')
if wires[8] == 'coconut': cut_wire(7)
add_key('none')
if wires[10] == 'gold': cut_wire(4)
add_key('none')
if wires[8] == 'charcoal': cut_wire(13)
add_key('none')
if wires[11] == 'crepe': cut_wire(1)
add_key('marmalade')
if cnt['marmalade'] == 5: cut_wire(15)
add_key('grape')
if cnt['grape'] >= 18: cut_wire(9)
add_key('none')
if wires[10] == 'silver': cut_wire(11)
add_key('ivory')
if cnt['ivory'] == 10: cut_wire(19)
add_key('none')
if wires[14] == 'sky': cut_wire(19)
add_key('none')
if wires[4] == 'pearl': cut_wire(8)
add_key('red')
if cnt['red'] == 12: cut_wire(20)
add_key('jade')
if cnt['jade'] >= 12: cut_wire(6)
add_key('gray')
if cnt['gray'] == 12: cut_wire(18)
add_key('chocolate')
if cnt['chocolate'] == 8: cut_wire(17)
add_key('black')
if cnt['black'] == 15: cut_wire(6)
add_key('none')
if wires[6] == 'emerald': cut_wire(6)
add_key('none')
if wires[15] == 'blue': cut_wire(8)
add_key('none')
if wires[11] == 'butter': cut_wire(1)
add_key('none')
if wires[6] == 'sandstone': cut_wire(7)
add_key('arctic')
if cnt['arctic'] == 16: cut_wire(15)
add_key('none')
if wires[5] == 'lemon': cut_wire(18)
add_key('none')
if wires[18] == 'pineapple': cut_wire(5)
add_key('penny')
if cnt['penny'] == 9: cut_wire(17)
add_key('buttermilk')
if cnt['buttermilk'] == 9: cut_wire(3)
add_key('berry')
if cnt['berry'] == 20: cut_wire(7)
add_key('basil')
if cnt['basil'] == 9: cut_wire(18)
add_key('none')
if wires[18] == 'charcoal': cut_wire(9)
add_key('none')
if wires[20] == 'azure': cut_wire(14)
add_key('granola')
if cnt['granola'] == 20: cut_wire(7)
add_key('plum')
if cnt['plum'] == 6: cut_wire(6)
add_key('none')
if wires[7] == 'bone': cut_wire(3)
add_key('banana')
if cnt['banana'] == 6: cut_wire(6)
add_key('charcoal')
if cnt['charcoal'] == 13: cut_wire(15)
add_key('none')
if wires[19] == 'tan': cut_wire(8)
add_key('bronze')
if cnt['bronze'] == 7: cut_wire(5)
add_key('none')
if wires[2] == 'sand': cut_wire(20)
add_key('oyster')
if cnt['oyster'] == 2: cut_wire(5)
add_key('bronze')
if cnt['bronze'] == 19: cut_wire(3)
add_key('seaweed')
if cnt['seaweed'] == 18: cut_wire(16)
add_key('banana')
if cnt['banana'] == 5: cut_wire(20)
add_key('none')
if wires[12] == 'pineapple': cut_wire(12)
add_key('none')
if wires[9] == 'charcoal': cut_wire(3)
add_key('orchid')
if cnt['orchid'] >= 16: cut_wire(7)
add_key('candy')
if cnt['candy'] == 7: cut_wire(12)
add_key('none')
if wires[4] == 'rouge': cut_wire(12)
add_key('lime')
if cnt['lime'] == 3: cut_wire(17)
add_key('crepe')
if cnt['crepe'] == 8: cut_wire(1)
add_key('scarlet')
if cnt['scarlet'] == 4: cut_wire(8)
add_key('flint')
if cnt['flint'] == 14: cut_wire(6)
add_key('porcelain')
if cnt['porcelain'] == 3: cut_wire(14)
add_key('coconut')
if cnt['coconut'] >= 11: cut_wire(11)
add_key('basil')
if cnt['basil'] == 7: cut_wire(5)
add_key('banana')
if cnt['banana'] == 4: cut_wire(18)
add_key('pickle')
if cnt['pickle'] == 8: cut_wire(1)
add_key('none')
if wires[7] == 'caramel': cut_wire(18)
add_key('crimson')
if cnt['crimson'] >= 9: cut_wire(16)
add_key('ash')
if cnt['ash'] == 10: cut_wire(14)
add_key('frost')
if cnt['frost'] >= 16: cut_wire(15)
add_key('none')
if wires[15] == 'fawn': cut_wire(19)
add_key('scarlet')
if cnt['scarlet'] == 13: cut_wire(16)
add_key('none')
if wires[17] == 'emerald': cut_wire(18)
add_key('candy')
if cnt['candy'] == 13: cut_wire(5)
add_key('brown')
if cnt['brown'] >= 10: cut_wire(15)
add_key('rouge')
if cnt['rouge'] == 11: cut_wire(10)
add_key('latte')
if cnt['latte'] == 16: cut_wire(14)
add_key('none')
if wires[3] == 'flint': cut_wire(13)
add_key('none')
if wires[3] == 'silver': cut_wire(2)
add_key('corn')
if cnt['corn'] >= 16: cut_wire(15)
add_key('none')
if wires[17] == 'wood': cut_wire(17)
add_key('fern')
if cnt['fern'] == 9: cut_wire(6)
add_key('none')
if wires[4] == 'hickory': cut_wire(4)
add_key('none')
if wires[12] == 'carrot': cut_wire(18)
add_key('jade')
if cnt['jade'] == 3: cut_wire(10)
add_key('penny')
if cnt['penny'] == 8: cut_wire(5)
add_key('iris')
if cnt['iris'] == 14: cut_wire(9)
add_key('watermelon')
if cnt['watermelon'] == 2: cut_wire(13)
add_key('none')
if wires[14] == 'arctic': cut_wire(5)
add_key('blue')
if cnt['blue'] == 9: cut_wire(3)
add_key('iris')
if cnt['iris'] == 7: cut_wire(8)
add_key('none')
if wires[8] == 'ivory': cut_wire(4)
add_key('coffee')
if cnt['coffee'] == 18: cut_wire(1)
add_key('none')
if wires[2] == 'wood': cut_wire(6)
add_key('arctic')
if cnt['arctic'] == 14: cut_wire(15)
add_key('none')
if wires[5] == 'plum': cut_wire(8)
add_key('brown')
if cnt['brown'] == 4: cut_wire(20)
add_key('rouge')
if cnt['rouge'] == 11: cut_wire(3)
add_key('daisy')
if cnt['daisy'] >= 14: cut_wire(19)
add_key('none')
if wires[11] == 'emerald': cut_wire(17)
add_key('none')
if wires[5] == 'violet': cut_wire(1)
add_key('brown')
if cnt['brown'] == 9: cut_wire(3)
add_key('none')
if wires[12] == 'ivory': cut_wire(19)
add_key('none')
if wires[5] == 'berry': cut_wire(3)
add_key('pickle')
if cnt['pickle'] >= 10: cut_wire(4)
add_key('rouge')
if cnt['rouge'] == 9: cut_wire(1)
add_key('none')
if wires[18] == 'amethyst': cut_wire(5)
add_key('none')
if wires[8] == 'coffee': cut_wire(8)
add_key('none')
if wires[9] == 'fawn': cut_wire(2)
add_key('obsidian')
if cnt['obsidian'] == 11: cut_wire(7)
add_key('tiger')
if cnt['tiger'] >= 12: cut_wire(1)
add_key('granola')
if cnt['granola'] == 3: cut_wire(8)
add_key('purple')
if cnt['purple'] == 12: cut_wire(5)
add_key('rose')
if cnt['rose'] >= 17: cut_wire(10)
add_key('none')
if wires[13] == 'lemon': cut_wire(4)
add_key('none')
if wires[14] == 'gold': cut_wire(11)
add_key('none')
if wires[1] == 'apricot': cut_wire(17)
add_key('black')
if cnt['black'] == 3: cut_wire(2)
add_key('none')
if wires[15] == 'magenta': cut_wire(12)
add_key('lead')
if cnt['lead'] == 1: cut_wire(20)
add_key('none')
if wires[10] == 'sandstone': cut_wire(16)
add_key('blood')
if cnt['blood'] == 8: cut_wire(11)
add_key('frost')
if cnt['frost'] == 1: cut_wire(11)
add_key('none')
if wires[5] == 'hickory': cut_wire(13)
add_key('white')
if cnt['white'] == 20: cut_wire(20)
add_key('purple')
if cnt['purple'] >= 14: cut_wire(11)
add_key('latte')
if cnt['latte'] == 5: cut_wire(3)
add_key('iron')
if cnt['iron'] == 1: cut_wire(8)
add_key('none')
if wires[2] == 'cotton': cut_wire(2)
add_key('none')
if wires[17] == 'lapis': cut_wire(18)
add_key('sky')
if cnt['sky'] == 4: cut_wire(19)
add_key('none')
if wires[18] == 'jade': cut_wire(5)
add_key('black')
if cnt['black'] == 15: cut_wire(4)
add_key('rosewood')
if cnt['rosewood'] == 8: cut_wire(14)
add_key('none')
if wires[13] == 'gray': cut_wire(4)
add_key('none')
if wires[14] == 'chocolate': cut_wire(14)
add_key('none')
if wires[6] == 'silver': cut_wire(3)
add_key('oyster')
if cnt['oyster'] == 10: cut_wire(1)
add_key('none')
if wires[20] == 'white': cut_wire(3)
add_key('none')
if wires[20] == 'ivory': cut_wire(10)
add_key('none')
if wires[11] == 'stone': cut_wire(19)
add_key('none')
if wires[2] == 'gray': cut_wire(19)
add_key('lead')
if cnt['lead'] == 2: cut_wire(6)
add_key('none')
if wires[2] == 'shortbread': cut_wire(16)
add_key('crepe')
if cnt['crepe'] == 16: cut_wire(4)
add_key('buttermilk')
if cnt['buttermilk'] == 3: cut_wire(2)
add_key('bone')
if cnt['bone'] == 15: cut_wire(15)
add_key('none')
if wires[18] == 'apricot': cut_wire(3)
add_key('peach')
if cnt['peach'] == 15: cut_wire(15)
add_key('none')
if wires[15] == 'latte': cut_wire(20)
add_key('none')
if wires[2] == 'arctic': cut_wire(8)
add_key('rust')
if cnt['rust'] == 17: cut_wire(15)
add_key('none')
if wires[15] == 'cobalt': cut_wire(5)
add_key('pineapple')
if cnt['pineapple'] >= 17: cut_wire(9)
add_key('none')
if wires[20] == 'violet': cut_wire(18)
add_key('grape')
if cnt['grape'] >= 9: cut_wire(9)
add_key('porcelain')
if cnt['porcelain'] == 2: cut_wire(10)
add_key('crepe')
if cnt['crepe'] == 14: cut_wire(10)
add_key('none')
if wires[10] == 'butter': cut_wire(6)
add_key('pineapple')
if cnt['pineapple'] == 2: cut_wire(19)
add_key('teal')
if cnt['teal'] == 10: cut_wire(11)
add_key('none')
if wires[18] == 'cloud': cut_wire(6)
add_key('none')
if wires[18] == 'cherry': cut_wire(14)
add_key('stone')
if cnt['stone'] == 11: cut_wire(9)
add_key('rust')
if cnt['rust'] == 15: cut_wire(15)
add_key('none')
if wires[16] == 'scarlet': cut_wire(6)
add_key('wine')
if cnt['wine'] == 15: cut_wire(2)
add_key('shamrock')
if cnt['shamrock'] == 13: cut_wire(4)
add_key('daisy')
if cnt['daisy'] >= 17: cut_wire(15)
add_key('none')
if wires[19] == 'shortbread': cut_wire(10)
add_key('none')
if wires[7] == 'fern': cut_wire(12)
add_key('teal')
if cnt['teal'] == 9: cut_wire(6)
add_key('coral')
if cnt['coral'] == 7: cut_wire(16)
add_key('none')
if wires[9] == 'berry': cut_wire(18)
add_key('butter')
if cnt['butter'] >= 10: cut_wire(18)
add_key('none')
if wires[9] == 'teal': cut_wire(6)
add_key('emerald')
if cnt['emerald'] == 9: cut_wire(6)
add_key('cloud')
if cnt['cloud'] == 6: cut_wire(12)
add_key('none')
if wires[4] == 'caramel': cut_wire(20)
add_key('none')
if wires[6] == 'stone': cut_wire(14)
add_key('chocolate')
if cnt['chocolate'] == 18: cut_wire(18)
add_key('gold')
if cnt['gold'] == 15: cut_wire(4)
add_key('ruby')
if cnt['ruby'] == 7: cut_wire(18)
add_key('coconut')
if cnt['coconut'] == 6: cut_wire(1)
add_key('none')
if wires[7] == 'brown': cut_wire(16)
add_key('none')
if wires[16] == 'carrot': cut_wire(14)
add_key('hickory')
if cnt['hickory'] == 13: cut_wire(11)
add_key('stone')
if cnt['stone'] == 11: cut_wire(10)
add_key('none')
if wires[10] == 'sand': cut_wire(4)
add_key('none')
if wires[2] == 'bronze': cut_wire(19)
add_key('none')
if wires[2] == 'cloud': cut_wire(2)
add_key('grape')
if cnt['grape'] == 3: cut_wire(11)
add_key('latte')
if cnt['latte'] == 7: cut_wire(11)
add_key('jade')
if cnt['jade'] == 16: cut_wire(12)
add_key('none')
if wires[18] == 'black': cut_wire(9)
add_key('none')
if wires[20] == 'pear': cut_wire(6)
add_key('sandstone')
if cnt['sandstone'] >= 8: cut_wire(16)
add_key('none')
if wires[13] == 'yellow': cut_wire(4)
add_key('pickle')
if cnt['pickle'] == 20: cut_wire(3)
add_key('azure')
if cnt['azure'] == 7: cut_wire(1)
add_key('none')
if wires[7] == 'banana': cut_wire(9)
add_key('none')
if wires[13] == 'rust': cut_wire(19)
add_key('none')
if wires[5] == 'purple': cut_wire(18)
add_key('pink')
if cnt['pink'] == 18: cut_wire(10)
add_key('none')
if wires[19] == 'pineapple': cut_wire(1)
add_key('none')
if wires[18] == 'wine': cut_wire(17)
add_key('ruby')
if cnt['ruby'] >= 8: cut_wire(13)
add_key('pear')
if cnt['pear'] == 1: cut_wire(9)
add_key('gold')
if cnt['gold'] == 6: cut_wire(13)
add_key('none')
if wires[19] == 'macaroon': cut_wire(17)
add_key('none')
if wires[11] == 'granola': cut_wire(4)
add_key('peach')
if cnt['peach'] == 19: cut_wire(9)
add_key('none')
if wires[10] == 'rouge': cut_wire(1)
add_key('none')
if wires[7] == 'orchid': cut_wire(16)
add_key('ivory')
if cnt['ivory'] == 18: cut_wire(10)
add_key('penny')
if cnt['penny'] == 17: cut_wire(5)
add_key('none')
if wires[7] == 'seaweed': cut_wire(14)
add_key('cherry')
if cnt['cherry'] == 13: cut_wire(14)
add_key('none')
if wires[8] == 'bronze': cut_wire(5)
add_key('green')
if cnt['green'] == 1: cut_wire(13)
add_key('candy')
if cnt['candy'] == 17: cut_wire(8)
add_key('none')
if wires[10] == 'eggplant': cut_wire(14)
add_key('rust')
if cnt['rust'] == 3: cut_wire(18)
add_key('wood')
if cnt['wood'] == 1: cut_wire(20)
add_key('pink')
if cnt['pink'] == 7: cut_wire(17)
add_key('none')
if wires[13] == 'cotton': cut_wire(19)
add_key('macaroon')
if cnt['macaroon'] == 15: cut_wire(1)
add_key('blue')
if cnt['blue'] >= 8: cut_wire(8)
add_key('iron')
if cnt['iron'] == 6: cut_wire(4)
add_key('navy')
if cnt['navy'] == 11: cut_wire(12)
add_key('none')
if wires[19] == 'watermelon': cut_wire(5)
add_key('fire')
if cnt['fire'] == 17: cut_wire(18)
add_key('arctic')
if cnt['arctic'] == 2: cut_wire(1)
add_key('fern')
if cnt['fern'] == 10: cut_wire(20)
add_key('plum')
if cnt['plum'] >= 16: cut_wire(12)
add_key('tiger')
if cnt['tiger'] == 3: cut_wire(13)
add_key('none')
if wires[1] == 'arctic': cut_wire(11)
add_key('ruby')
if cnt['ruby'] == 19: cut_wire(20)
add_key('pearl')
if cnt['pearl'] == 10: cut_wire(4)
add_key('corn')
if cnt['corn'] == 8: cut_wire(13)
add_key('none')
if wires[4] == 'caramel': cut_wire(6)
add_key('none')
if wires[6] == 'cotton': cut_wire(6)
add_key('squash')
if cnt['squash'] == 2: cut_wire(12)
add_key('none')
if wires[18] == 'orange': cut_wire(15)
add_key('yellow')
if cnt['yellow'] == 12: cut_wire(3)
add_key('none')
if wires[9] == 'coral': cut_wire(4)
add_key('none')
if wires[6] == 'squash': cut_wire(12)
add_key('tiger')
if cnt['tiger'] == 2: cut_wire(8)
add_key('green')
if cnt['green'] >= 11: cut_wire(17)
add_key('wood')
if cnt['wood'] >= 9: cut_wire(8)
add_key('orange')
if cnt['orange'] == 1: cut_wire(7)
add_key('butter')
if cnt['butter'] == 17: cut_wire(10)
add_key('frost')
if cnt['frost'] == 6: cut_wire(17)
add_key('arctic')
if cnt['arctic'] >= 7: cut_wire(8)
add_key('grape')
if cnt['grape'] >= 11: cut_wire(9)
add_key('none')
if wires[9] == 'latte': cut_wire(8)
add_key('none')
cut_wire(1)
